In [1]:
import pandas as pd
import plotly.express as px

In [2]:
# reading the csv file
df_population_raw = pd.read_csv('population_total.csv')
# dropping null values
df_population_raw.dropna(inplace=True)
# making a pivot table
df_pivot = df_population_raw.pivot(index='year', columns='country',
                                        values='population')
# selecting some countries
df_pivot = df_pivot[['United States', 'India', 'China', 
                          'Indonesia', 'Brazil']]
# showing pivot table
df_pivot

country  United States         India         China    Indonesia       Brazil
year
1955.0     171685336.0  4.098806e+08  6.122416e+08   77273425.0   62533919.0
1960.0     186720571.0  4.505477e+08  6.604081e+08   87751068.0   72179226.0
1965.0     199733676.0  4.991233e+08  7.242190e+08  100267062.0   83373530.0
1970.0     209513341.0  5.551898e+08  8.276014e+08  114793178.0   95113265.0
1975.0     219081251.0  6.231029e+08  9.262409e+08  130680727.0  107216205.0
1980.0     229476354.0  6.989528e+08  1.000089e+09  147447836.0  120694009.0
1985.0     240499825.0  7.843600e+08  1.075589e+09  164982451.0  135274080.0
1990.0     252120309.0  8.732778e+08  1.176884e+09  181413402.0  149003223.0
1995.0     265163745.0  9.639226e+08  1.240921e+09  196934260.0  162019896.0
2000.0     281710909.0  1.056576e+09  1.290551e+09  211513823.0  174790340.0
2005.0     294993511.0  1.147610e+09  1.330776e+09  226289470.0  186127103.0
2010.0     309011475.0  1.234281e+09  1.368811e+09  241834215.0  195713635.0
2015.0     320878310.0  1.310152e+09  1.406848e+09  258383256.0  204471769.0
2016.0     323015995.0  1.324517e+09  1.414049e+09  261556381.0  206163053.0
2017.0     325084756.0  1.338677e+09  1.421022e+09  264650963.0  207833823.0
2018.0     327096265.0  1.352642e+09  1.427648e+09  267670543.0  209469323.0
2019.0     329064917.0  1.366418e+09  1.433784e+09  270625568.0  211049527.0
2020.0     331002651.0  1.380004e+09  1.439324e+09  273523615.0  212559417.0

# Lineplot

In [5]:
fig = px.line(df_pivot, title='Population (1955-2020)',
              labels={'value':'Population','year':'Years','variable':'Country'})

#Updating the theme
fig.update_layout(template='ggplot2')

#Displaying the lineplot
fig.show()

# Barplot

In [6]:
# selecting only one year (2020)
df_pivot_2020 = df_pivot[df_pivot.index.isin([2020])]
# transpose dataframe from rows to columns or viceversa
df_pivot_2020 = df_pivot_2020.T

In [ ]:
fig = px.bar(df_pivot_2020,barmode='group',
             labels={'values':'Population','country':'Countries'})

#Display the single Bargraph
fig.show()

## Barplot grouped by “n” variables

In [13]:
# selecting a few years
df_pivot_sample = df_pivot[df_pivot.index.isin([1980, 1990, 2000, 2010, 2020])]

In [15]:
fig = px.bar(df_pivot_sample,barmode='group')

fig.show()

# Piechart

In [16]:
# changing column name 
df_pivot_2020.rename(columns={2020:'2020'}, inplace=True)

In [22]:
df_pivot_2020 = df_pivot_2020.reset_index()
df_pivot_2020

year  index        country          2020
0         0  United States  3.310027e+08
1         1          India  1.380004e+09
2         2          China  1.439324e+09
3         3      Indonesia  2.735236e+08
4         4         Brazil  2.125594e+08

In [21]:
px.pie(df_pivot_2020,values='2020',names='country',title='Population distribution in 2020')

# Boxplot

In [27]:
#Single Box plot

df_pivot_single_country = df_pivot[['India']]
fig = px.box(df_pivot_single_country,labels={'value':'Population','country':'Country'})
fig.show()

In [30]:
# Box plot(multiple columns)
px.box(df_pivot,labels={'value':'Population','country':'Country'})

# Histogram

In [34]:
fig = px.histogram(df_pivot,nbins=3,barmode='overlay')

fig.show()

# ScatterPlot

In [36]:
px.scatter(df_pivot,labels={'value':'Population','year':'Years'})